from my_project.auth.domain.orders.specialities import Specialties
from my_project.auth.domain.orders.symptomes import Symptomes
from my_project.auth.domain.orders.diagnoses import Diagnoses
from my_project.auth.domain.orders.patients import Patients
from my_project.auth.domain.orders.doctors import Doctors
from my_project.auth.domain.orders.appointments import Appointments
from my_project.auth.domain.orders.illnesses import Illnesses
from my_project.auth.domain.orders.scedules import Schedules
from my_project.auth.domain.orders.recoveryprotocol import RecoveryProtocol
from my_project.auth.domain.orders.appointmentbookings import AppointmentBookings
from my_project.auth.domain.orders.billing import Billing
from my_project.auth.domain.orders.doctorsymptomes import DoctorSymptomes